definitions:
  app.AddProductRequest:
    properties:
      kodeProduk:
        type: string
      kuantitas:
        type: integer
      namaProduk:
        type: string
    required:
    - kodeProduk
    - kuantitas
    - namaProduk
    type: object
  app.DeleteProductRequest:
    properties:
      kodeProduk:
        type: string
    required:
    - kodeProduk
    type: object
  helper.Response:
    properties:
      data: {}
      errors:
        type: string
      success:
        type: boolean
    type: object
host: localhost:8081
info:
  contact: {}
  description: Haioo Cart Service
  title: Haioo
  version: "1.0"
paths:
  /api/v1/cart/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: request data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/app.AddProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.Response'
      summary: Add product to cart.
      tags:
      - Add Product
  /api/v1/cart/delete:
    delete:
      consumes:
      - application/json
      parameters:
      - description: request data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/app.DeleteProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.Response'
      summary: Delete product in cart.
      tags:
      - Delete Product
  /api/v1/cart/show:
    get:
      consumes:
      - application/json
      parameters:
      - description: Request data nama produk
        in: query
        name: namaProduk
        type: string
      - in: query
        name: kuantitas
        description: Sort order by kuantitas
        type: string
        enum: [asc, desc]
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.Response'
      summary: Show product in cart.
      tags:
      - Show Cart
swagger: "2.0"
